version: "3.1"

services:
  mdb-web:
    image: odoo:19.0
    container_name: mdb_demo_2
    restart: unless-stopped
    depends_on:
      - mdbdb
    ports:
      - "8071:8069"
      - "8074:8072"
    volumes:
      - odoo-data-2:/var/lib/odoo
      - /opt/odoo/Odoo18/config2/odoo.conf:/opt/odoo/odoo.conf
      - /opt/odoo/Odoo18/addonsv2/mt/extra-addons:/mnt/extra-addons
      - /opt/odoo/Odoo18/scripts/entrypoint.sh:/custom-entrypoint.sh
      - /opt/odoo/Odoo18/scripts/wait-for-psql.py:/wait-for-psql.py
    environment:
      HOST: mdbdb
      USER: null
      PASSWORD: odoo
      ODOO_RC: /opt/odoo/odoo.conf
    entrypoint: ["/custom-entrypoint.sh"]

  mdbdb:
    image: postgres:16.0
    container_name: demodb_2
    restart: unless-stopped
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db-data-2:/var/lib/postgresql/data

volumes:
  odoo-data-2:
  db-data-2:
