version: "3.1"

services:
  mdb-web:
    image: odoo:19.0
    container_name: test19
    restart: unless-stopped
    depends_on:
      - mdbdb
    ports:
      - "8072:8069"
      - "8075:8072"
    volumes:
      - test19-odoo-data-2:/var/lib/odoo
      - /opt/odoo/test_odoo_19/config2/odoo.conf:/opt/odoo/odoo.conf
      - /opt/odoo/test_odoo_19/addonsv2/mt/extra-addons:/mnt/extra-addons
      - /opt/odoo/test_odoo_19/scripts/entrypoint.sh:/custom-entrypoint.sh
      - /opt/odoo/test_odoo_19/scripts/wait-for-psql.py:/wait-for-psql.py
    environment:
      HOST: mdbdb
      USER: null
      PASSWORD: odoo
      ODOO_RC: /opt/odoo/odoo.conf
    entrypoint: ["/custom-entrypoint.sh"]

  mdbdb:
    image: postgres:16.0
    container_name: testdb_2
    restart: unless-stopped
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - test19-db-data-2:/var/lib/postgresql/data

volumes:
  test19-odoo-data-2:
  test19-db-data-2:
